import React, { useEffect, useState } from 'react'
import apiClient from '../api/apiClient'
import DataTable from './DataTable.jsx'
import { PageHeader, showError } from './SimplePanels.jsx'

export default function IntegrationOutputPanel(){
  const [integrations,setIntegrations]=useState([]),[notifications,setNotifications]=useState([]),[reports,setReports]=useState([]),[exportMessage,setExportMessage]=useState('')
  const integrationColumns=['integration_id','integration_time','target_system','direction','api_name','status','message']
  const notificationColumns=['notification_id','notification_time','channel_type','receiver','subject','send_status','related_work_order_no']
  const reportColumns=['report_job_id','report_time','report_type','report_name','file_format','job_status','created_by']
  async function load(){ setIntegrations((await apiClient.get('/architecture/integrations')).data||[]); setNotifications((await apiClient.get('/architecture/notifications')).data||[]); setReports((await apiClient.get('/architecture/reports')).data||[]) }
  async function createIntegration(){ await apiClient.post('/architecture/integrations/demo').catch(showError); await load() }
  async function createNotification(){ await apiClient.post('/architecture/notifications/demo').catch(showError); await load() }
  function directDownload(path,message){ setExportMessage(message); const base=apiClient.defaults.baseURL||''; const sep=path.includes('?')?'&':'?'; const url=`${base}${path}${sep}_t=${Date.now()}`; const a=document.createElement('a'); a.href=url; a.target='_blank'; a.rel='noopener'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>load(),1500) }
  async function exportReport(format){ directDownload(`/architecture/reports/export-file/${format}`,`正在產生 ${format.toUpperCase()} 報表，瀏覽器會開始下載...`) }
  function fileHint(report){ const path=report.file_path||''; if(path.startsWith('/reports/')) return '舊 Demo 路徑，下載時會自動重產'; return path }
  async function download(report){ directDownload(`/architecture/reports/download/${report.report_job_id}`,'正在下載報表...') }
  async function deleteReport(report){ if(!confirm(`確定刪除報表：${report.report_name||report.report_job_id}？`)) return; await apiClient.delete(`/architecture/reports/${report.report_job_id}`).catch(showError); setExportMessage('報表已刪除'); await load() }
  async function deleteAllReports(){ if(!confirm('確定刪除全部報表紀錄與已產生檔案？')) return; await apiClient.delete('/architecture/reports').catch(showError); setExportMessage('全部報表已刪除'); await load() }
  async function cleanupDemoReports(){ await apiClient.post('/architecture/reports/cleanup-demo').catch(showError); setExportMessage('舊 Demo 假路徑報表已清除'); await load() }
  useEffect(()=>{load()},[])
  const metric=[['系統整合',integrations.length,'MES / ERP / WMS'],['通知紀錄',notifications.length,'Email / LINE / Teams'],['報表輸出',reports.length,'Excel / PDF / BI / CSV']]
  return <div className="page"><PageHeader title="對外整合輸出" subtitle="MES / ERP / WMS 整合紀錄、Email / LINE / Teams 通知，以及可真正下載的 Excel / PDF / BI / CSV 報表。"><button className="primary-btn" onClick={createIntegration}>新增整合紀錄 Demo</button><button onClick={createNotification}>新增通知 Demo</button><button onClick={()=>exportReport('excel')}>輸出 Excel</button><button onClick={()=>exportReport('pdf')}>輸出 PDF</button><button onClick={()=>exportReport('html')}>輸出 BI HTML</button><button onClick={()=>exportReport('csv')}>輸出 CSV</button><button className="danger-outline-btn" onClick={deleteAllReports}>刪除全部報表</button><button onClick={load}>重新整理</button></PageHeader>{exportMessage&&<div className="export-message">{exportMessage}</div>}<div className="metric-grid">{metric.map(x=><div className="metric-card" key={x[0]}><div className="metric-label">{x[0]}</div><div className="metric-value">{x[1]}</div><div className="metric-hint">{x[2]}</div></div>)}</div><div className="report-design-card"><div className="report-preview"><div className="report-preview-header"><div><strong>MK-AIPS 智慧排程報表</strong><span>CNC 智慧電表 / OEE / DQN</span></div><div className="report-preview-badge">正式輸出</div></div><div className="report-preview-kpis">{['總用電 kWh','平均功率','最大需量','異常機台','碳排 kg'].map(x=><div key={x}><span>{x}</span><b>{x==='碳排 kg'?'0.494 係數':x==='最大需量'?'Demand':x==='異常機台'?'THD / Power':x==='平均功率'?'kW':'自動彙總'}</b></div>)}</div></div></div><div className="card"><h2>MES / ERP / WMS 整合紀錄</h2><DataTable columns={integrationColumns} rows={integrations}/></div><div className="card"><h2>Email / LINE / Teams 通知</h2><DataTable columns={notificationColumns} rows={notifications}/></div><div className="card"><h2>Excel / PDF / BI / CSV 報表輸出</h2><DataTable columns={reportColumns} rows={reports}/><div className="report-list">{reports.map(report=><div key={report.report_job_id} className="report-item"><div><strong>{report.report_name}</strong><span>{report.file_format}｜{report.report_time}｜{fileHint(report)}</span></div><div className="report-actions"><button className="primary-btn" onClick={()=>download(report)}>下載</button><button className="danger-outline-btn" onClick={()=>deleteReport(report)}>刪除</button></div></div>)}</div></div></div>
}
